defmodule Wasomi.Catalog.Workers.AttachLectureOverviewVideoWorker do
  @moduledoc """
  Attaches a `:ready` AI video-overview generation's video as the
  lecture's actual playable video — a lecture's real video is either
  uploaded by an admin or generated by AI, never both, and either way it
  ends up in the same `Lecture.video_asset_id`/`video_provider`/
  `duration_seconds` fields.

  A Mux asset is created directly from the generated file's own storage
  URL (Mux fetches it itself — no proxying bytes through this app, the
  same way `Wasomi.Media.Mux.create_upload/2` never touches the actual
  video bytes for a browser upload either). Mux asset processing is
  asynchronous, so this job polls for readiness via Oban's `{:snooze, _}`
  return (reschedules itself without counting as a failed attempt)
  instead of blocking or needing a second worker.
  """

  use Oban.Worker, queue: :lecture_overview, max_attempts: 5

  alias Wasomi.{Catalog, Media, Repo}

  @snooze_seconds 10

  # Each invocation does at most one network call (the Mux HTTP client
  # itself already times out at 15s, see `Wasomi.Media.Mux.request/3`)
  # before returning or snoozing — 2 minutes is a generous bound on a
  # single attempt, not the overall poll-until-ready duration (snoozing
  # doesn't count against this; only how long one execution may run).
  @impl Oban.Worker
  def timeout(_job), do: :timer.minutes(2)

  @impl Oban.Worker
  def perform(%Oban.Job{
        attempt: attempt,
        max_attempts: max_attempts,
        args: %{"generation_id" => generation_id}
      }) do
    generation =
      generation_id
      |> Catalog.get_overview_generation!()
      |> Repo.preload([:lecture, :requested_by])

    case run(generation) do
      :ok ->
        :ok

      {:snooze, seconds} ->
        {:snooze, seconds}

      {:error, reason} ->
        if attempt >= max_attempts do
          Catalog.mark_overview_video_attach_failed(generation, format_failure(reason))
        end

        {:error, reason}
    end
  end

  defp run(%{attach_asset_id: nil} = generation) do
    with {:ok, url} <- storage().download_url(generation.video_storage_key),
         {:ok, %{asset_id: asset_id}} <-
           Media.create_asset_from_url(generation.requested_by, generation.lecture, url) do
      Catalog.record_overview_video_attach_asset(generation, asset_id)
      {:snooze, @snooze_seconds}
    end
  end

  defp run(%{attach_asset_id: asset_id} = generation) when is_binary(asset_id) do
    case Media.asset_status(generation.requested_by, asset_id) do
      {:ok, {:ready, playback_id, duration}} ->
        with {:ok, _lecture} <-
               Catalog.attach_lecture_video(generation.lecture, playback_id, duration) do
          Catalog.mark_overview_video_attached(generation)
          :ok
        end

      {:ok, status} when status in [:waiting, :processing] ->
        {:snooze, @snooze_seconds}

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp format_failure(%Ecto.Changeset{} = changeset) do
    Ecto.Changeset.traverse_errors(changeset, fn {msg, opts} ->
      Regex.replace(~r"%{(\w+)}", msg, fn _, key ->
        opts |> Keyword.get(String.to_existing_atom(key), key) |> to_string()
      end)
    end)
    |> inspect()
  end

  defp format_failure({:mux, %{"messages" => [_ | _] = messages}}),
    do: "Mux rejected the request (#{Enum.join(messages, " ")})"

  defp format_failure({:mux, %{"type" => type}}), do: "Mux rejected the request (#{type})"

  defp format_failure({:mux, status, _body}) when is_integer(status),
    do: "Mux returned an unexpected response (HTTP #{status})"

  defp format_failure(reason), do: inspect(reason)

  defp storage,
    do: Application.get_env(:wasomi, :catalog_storage, Wasomi.Catalog.Storage.R2)
end
